### ISSUE TITLE
Invalid gemspec in [ZenTest.gemspec]: Illformed requirement ["< 3.0, >= 1.8"]

### ISSUE THREAD

**Issue by lucaskanashiro** [seattlerb/zentest#68]
I have this error in version 4.11.1, could you try to fix it?

Thanks!

**Comment by zenspider** [comment]
Please update your rubygems

**Comment by zenspider** [comment]
No response. Closing.

**Comment by alowde-catapult** [comment]
I get the same error using rubygems v2.6.12 and ruby 1.9.3p551. Passing the requirements as an array of two strings (["< 3.0", ">= 1.8"]) instead of a single string ("< 3.0, >= 1.8") resolves the issue. Would you consider updating the gemspec?

**Comment by zenspider** [comment]
Do you have a repro? It works fine here:

```
10072 % rm -rf xxx; ruby -v; gem -v; gem i -i xxx ZenTest
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
2.6.8
Fetching: ZenTest-4.11.1.gem (100%)
Successfully installed ZenTest-4.11.1
1 gem installed
10083 % rbenv install 1.9.3-p551
...
10095 % rbenv shell 1.9.3-p551 
10096 % gem update --system
...
10116 % rm -rf xxx; ruby -v; gem -v; gem i -i xxx ZenTest
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin16.5.0]
2.6.12
Fetching: ZenTest-4.11.1.gem (100%)
Successfully installed ZenTest-4.11.1
1 gem installed
```

**Comment by alowde-catapult** [comment]
Hi, sorry for the inaccurate information. I can reproduce with rubygems 1.8.23, not 2.6.12 - relevant because 1.8.23 is installed by default with Ruby 1.9.3p551.

Reproduced using RVM and a named Ruby as RVM only supports one version of rubygems installed per Ruby.

```
  # mkdir test-zentest
  # echo 'ruby-1.9.3-p551-testing' > test-zentest/.ruby-version
  # echo 'test-zentest' > test-zentest/.ruby-gemset
  # cd test-zentest
ruby-1.9.3-p551-testing is not installed.
To install do: 'rvm install ruby-1.9.3-p551-testing'
  # rvm install ruby-1.9.3-p551-testing
...
 # ruby -v
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin13.4.0]  
 # gem -v
1.8.23
 # gem install ZenTest
Fetching: ZenTest-4.11.1.gem (100%)
Invalid gemspec in [/Users/.../.rvm/gems/ruby-1.9.3-p551@test-zentest/specifications/ZenTest-4.11.1.gemspec]: Illformed requirement ["< 3.0, >= 1.8"]
Successfully installed ZenTest-4.11.1
 ```

When running `gem install` it appears to work OK despite displaying the error, when using `bundle install` it was causing the bundle to fail.

Hope this helps, I understand it may not be worth resolving given the age of Ruby, rubygems here. We can work around it by updating rubygems to 2.6.12 and possibly using a named Ruby if this causes issues for other packages.

**Comment by alowde-catapult** [comment]
OK, this was a dupe of #28. Please ignore.
